apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: true
  - name: Orchestrator API
    type: simpod-json-datasource
    access: proxy
    uid: orchestrator-api
    url: http://orchestrator:8000
    jsonData:
      httpHeaderName1: X-Orchestrator-User
    secureJsonData:
      httpHeaderValue1: grafana
    editable: true
